apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: canopy-ui
  description: The UI library for our new EHR Application.
  tags:
    - typescript
    - canopy-ui
    - react
    - design-system
    - component-library
    - ui
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: raintreeinc/canopy-ui
    npm/package: canopy-ui
    npm/registry: common-ts-libs
  links:
    - url: https://106367354196-km2g4hrq.us-east-1.console.aws.amazon.com/codesuite/codeartifact/d/106367354196/raintree-libs/r/common-ts-libs/p/npm/canopy-ui/versions?region=us-east-1&package-versions-meta=eyJmIjp7fSwicyI6e30sIm4iOjIwLCJpIjowfQ
      title: CodeArtifact
      icon: npm
spec:
  type: library
  lifecycle: experimental
  owner: engineering
  system: ehr